name: Releases

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  release:
    name: "Releases"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: "Build"
        run: "make"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "lib/*.so"
          tag: "0.1.4"
