name: Releases

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  release:
    name: "Releases"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: "Config"
        run: "cmake -DCMAKE_BUILD_TYPE:STRING=Release -S. -B./build"

      - name: "Build"
        run: "cmake --build ./build --config Release --target KiteSTL -j 22 --"

      - name: "Pack"
        run: "tar -cf archive.tar build/*.so inc"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "archive.tar"
          tag: "0.2.9"
